[workspace]
members = ["contracts/*",  "e2e"]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/tasiov/infinity-pool"
description = "An NFT AMM protocol written for CosmWasm"
license = "BUSL-1.1"

[profile.release.package.infinity-pool]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
