version: 2.1

workflows:
  artifacts:
    jobs:
      - optimize_x86_64:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/
      - optimize_arm64:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/
      - upload_artifacts:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/
          requires:
            - optimize_x86_64
            - optimize_arm64

jobs:
  optimize_x86_64:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: optimize x86_64 contracts
          command: ./scripts/optimize.sh
      - run:
          name: Show x86_64 data
          command: |
            ls -l artifacts
            cat artifacts/checksums.txt
      - store_artifacts:
          path: artifacts
          destination: x86_64-artifacts

  optimize_arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: optimize arm64 contracts
          command: ./scripts/optimize-arm.sh
      - run:
          name: Show ARM64 data
          command: |
            ls -l artifacts
            cat artifacts/checksums.txt
      - store_artifacts:
          path: artifacts
          destination: arm64-artifacts

  upload_artifacts:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - checkout
      - run:
          name: Combine artifacts
          command: |
            mkdir new_directory
            cp -r x86_64-artifacts/* artifacts/
            cp -r arm64-artifacts/* artifacts/
            rm artifacts/checksums_intermediate.txt
            cat x86_64-artifacts/checksums.txt arm64-artifacts/checksums.txt > artifacts/checksums.txt

      - run:
          name: Upload artifacts
          command: |
            TAG="$CIRCLE_TAG"
            TITLE="$TAG"
            ghr -t "$GITHUB_TOKEN" \
              -u "$CIRCLE_PROJECT_USERNAME" \
              -r "$CIRCLE_PROJECT_REPONAME" \
              -c "$CIRCLE_SHA1" \
              -n "$TITLE" \
              -delete \
              -generatenotes \
              "$TAG" ./artifacts/
