version: 2.1

workflows:
  artifacts:
    jobs:
      - optimize_x86_64:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/
      - optimize_arm64:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/
      - upload_artifacts:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/
          requires:
            - optimize_x86_64
            - optimize_arm64

jobs:
  optimize_x86_64:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: optimize x86_64 contracts
          command: ./scripts/optimize.sh
      - run:
          name: copy x86_64 artifacts
          command: |
            mkdir x86_64-artifacts
            cp artifacts/* x86_64-artifacts/
      - persist_to_workspace:
          root: .
          paths:
            - x86_64-artifacts/

  optimize_arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: optimize arm64 contracts
          command: ./scripts/optimize-arm.sh
      - run:
          name: copy arm64 artifacts
          command: |
            mkdir arm64-artifacts
            cp artifacts/* arm64-artifacts/
      - persist_to_workspace:
          root: .
          paths:
            - arm64-artifacts/

  upload_artifacts:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: /workspace
      - checkout
      - run:
          name: Combine artifacts
          command: |
            mkdir new_directory
            mkdir ./artifacts/
            cp -r /workspace/x86_64-artifacts/* ./artifacts/
            cp -r /workspace/arm64-artifacts/* ./artifacts/
            rm ./artifacts/checksums_intermediate.txt
            cat /workspace/x86_64-artifacts/checksums.txt /workspace/arm64-artifacts/checksums.txt > ./artifacts/checksums.txt

      - run:
          name: Upload artifacts
          command: |
            TAG="$CIRCLE_TAG"
            TITLE="$TAG"
            ghr -t "$GITHUB_TOKEN" \
              -u "$CIRCLE_PROJECT_USERNAME" \
              -r "$CIRCLE_PROJECT_REPONAME" \
              -c "$CIRCLE_SHA1" \
              -n "$TITLE" \
              -delete \
              -generatenotes \
              "$TAG" ./artifacts/
