name: Build and Upload Contracts

on:
  release:
    types: [created, edited]

jobs:
  build_and_upload_contracts:
    runs-on: ubuntu-latest

    steps:
      - uses: extractions/setup-just@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build development contracts
        run: just optimize

      - name: Show data
        run: |
          ls -l artifacts
          cat artifacts/checksums.txt

      - name: Publish artifacts on GitHub
        uses: tcnksm/ghr@v0.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          tag: ${{ github.event.release.tag_name }}
          title: ${{ github.event.release.tag_name }}
          delete: true
          files: ./artifacts/
